version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-contentseen:
    container_name: whirlpool-contentseen
    entrypoint: bash ./scripts/wait-for-it.sh
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-contentseen-dev
    restart: on-failure
